name: ServerPlugin
main: me.ende124.testplugin.ServerPlugin
version: 1.0

commands:
   heal:
      description: Heals you
      usage: /<command> [player]

   goto:
      description: Goto a player
      usage: /<command> <player>

   bring:
      description: Bring a player
      usage: /<command> <player>

   setwarp:
      description: Set a new warp
      usage: /<command> <name> [description]
      
   warps:
      description: List the warps
      usage: /<command>
      
   warp:
      description: Warp
      usage: /<command> <warp>
      
   delwarp:
      description: Delete a warp
      usage: /<command> <warp>
      
   kit:
      description: Kits!
      usage: /<command> <kit>
      
   acolor:
      description: Color armor
      usage: /<command>