name: ServerPlugin
main: me.ende124.testplugin.ServerPlugin
version: 1.0

commands:
   heal:
      description: Heals you
      usage: /<command> [player]

   goto:
      description: Goto a player
      usage: /<command> <player>

   bring:
      description: Bring a player
      usage: /<command> <player>

   setwarp:
      description: Set a new warp
      usage: /<command> <name>